name: hello  # Name of the workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run your action
        uses: ../  # Assuming your action is in the root directory of your repository
        with:
          name: "Sanket"
